<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_E2E_Checkout_InternalData</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7fdd046b-d44f-4cff-b056-538510214528</testSuiteGuid>
   <testCaseLink>
      <guid>890a201a-9ed9-4792-883d-cf7b5bc897c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reusable Test Case/TC Validasi Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f82e81d7-9362-45f8-9fd3-42b4e0d37f45</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data/internal data login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f82e81d7-9362-45f8-9fd3-42b4e0d37f45</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ddb8732b-1f8e-4fc7-8085-d187fd208791</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f82e81d7-9362-45f8-9fd3-42b4e0d37f45</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>70cbe48a-4cd9-4a0f-ac16-c0a823cc5aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f82e81d7-9362-45f8-9fd3-42b4e0d37f45</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>payment</value>
         <variableId>61f15de3-1f5e-4017-8774-6129aa31bf1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fd2a37f-8ecd-483a-b118-2b6d2f0b9cc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a8ab439-6c43-4a0c-a28d-31ac7929ab9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5816e79b-4678-45d1-adca-fcd93e6d9b96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fbaf202-80e1-4377-90f7-e6046e280382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26fe4fd7-739a-4f08-9326-9e462b122540</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29cc4a40-a7fd-4ea2-8a1a-f8f766f912e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77603c1-b256-4432-bb3c-4b655dd5296b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
