<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payment_method_bacs</name>
   <tag></tag>
   <elementGuidId>affce3f9-fb93-4487-8881-c7b8bb8c7e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_method_bacs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_bacs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Direct Bank Transfer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7649281f-5593-4ba5-beda-cacde939ed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_bacs</value>
      <webElementGuid>2c1c649b-7a2d-42da-8248-59d10d6de492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c40da1cc-d8ac-4676-9a1c-edad321dbeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>d25ccf94-3142-4954-8f5b-b8e38ffc7912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>898eb5c8-ab60-47d2-9975-d9e989f30577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bacs</value>
      <webElementGuid>5e90feba-0415-4d15-ba1a-7f2dca041f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_bacs&quot;)</value>
      <webElementGuid>98113f78-baab-4ac7-95f7-6c8bd0d55c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_bacs']</value>
      <webElementGuid>fe1139c9-bac2-47ae-af5d-ae84c390a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li/input</value>
      <webElementGuid>9bd800ee-a88a-4047-b4bb-5d1992d633c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>d7c9b50b-5866-4103-8d86-bd3ea81d1cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_bacs' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>99d2c0e4-0f4c-41b2-9577-6260d5c2cf6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
